// GENERATED FILE. DO NOT EDIT BY HAND.
// Source: src/timescanAssets/registry.js

const TIMESCAN_STRIP_BASE = `${String(import.meta.env?.BASE_URL || "/").replace(/\/?$/, "/")}timescan-glyph-strips/`

const timescanGlyphStrips = {
  "home.heading": {
    width: 1387,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}home-heading/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}home-heading/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}home-heading/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}home-heading/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}home-heading/flicker-4.svg`,
    ],
  },
  "home.lead": {
    width: 1317,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}home-lead/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}home-lead/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}home-lead/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}home-lead/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}home-lead/flicker-4.svg`,
    ],
  },
  "services.eyebrow": {
    width: 1463,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-eyebrow/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-eyebrow/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-eyebrow/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-eyebrow/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-eyebrow/flicker-4.svg`,
    ],
  },
  "services.heading": {
    width: 1243,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-heading/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-heading/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-heading/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-heading/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-heading/flicker-4.svg`,
    ],
  },
  "services.lead": {
    width: 1321,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-lead/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-lead/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-lead/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-lead/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-lead/flicker-4.svg`,
    ],
  },
  "services.studio-rental.title": {
    width: 1368,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-studio-rental-title/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-studio-rental-title/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-title/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-title/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-title/flicker-4.svg`,
    ],
  },
  "services.studio-rental.image": {
    width: 1424,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-studio-rental-image/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-studio-rental-image/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-image/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-image/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-image/flicker-4.svg`,
    ],
  },
  "services.studio-rental.bullet.0": {
    width: 1285,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-0/flicker-4.svg`,
    ],
  },
  "services.studio-rental.bullet.1": {
    width: 1118,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-1/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-1/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-1/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-1/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-1/flicker-4.svg`,
    ],
  },
  "services.studio-rental.bullet.2": {
    width: 1254,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-2/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-2/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-2/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-2/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-2/flicker-4.svg`,
    ],
  },
  "services.studio-rental.bullet.3": {
    width: 1315,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-3/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-3/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-3/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-3/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-studio-rental-bullet-3/flicker-4.svg`,
    ],
  },
  "services.music-teaching.title": {
    width: 1285,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-music-teaching-title/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-music-teaching-title/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-title/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-title/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-title/flicker-4.svg`,
    ],
  },
  "services.music-teaching.image": {
    width: 1360,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-music-teaching-image/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-music-teaching-image/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-image/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-image/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-image/flicker-4.svg`,
    ],
  },
  "services.music-teaching.bullet.0": {
    width: 1313,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-0/flicker-4.svg`,
    ],
  },
  "services.music-teaching.bullet.1": {
    width: 1301,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-1/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-1/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-1/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-1/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-1/flicker-4.svg`,
    ],
  },
  "services.music-teaching.bullet.2": {
    width: 1364,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-2/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-2/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-2/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-2/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-2/flicker-4.svg`,
    ],
  },
  "services.music-teaching.bullet.3": {
    width: 1264,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-3/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-3/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-3/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-3/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-music-teaching-bullet-3/flicker-4.svg`,
    ],
  },
  "services.other-services.title": {
    width: 1214,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-other-services-title/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-other-services-title/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-title/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-title/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-title/flicker-4.svg`,
    ],
  },
  "services.other-services.image": {
    width: 1413,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-other-services-image/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-other-services-image/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-image/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-image/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-image/flicker-4.svg`,
    ],
  },
  "services.other-services.bullet.0": {
    width: 1170,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-other-services-bullet-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-0/flicker-4.svg`,
    ],
  },
  "services.other-services.bullet.1": {
    width: 1353,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-other-services-bullet-1/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-1/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-1/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-1/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-1/flicker-4.svg`,
    ],
  },
  "services.other-services.bullet.2": {
    width: 1183,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-other-services-bullet-2/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-2/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-2/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-2/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-2/flicker-4.svg`,
    ],
  },
  "services.other-services.bullet.3": {
    width: 1210,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}services-other-services-bullet-3/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-3/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-3/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-3/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}services-other-services-bullet-3/flicker-4.svg`,
    ],
  },
  "portfolio.heading": {
    width: 1334,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-heading/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-heading/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-heading/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-heading/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-heading/flicker-4.svg`,
    ],
  },
  "portfolio.lead": {
    width: 1307,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-lead/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-lead/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-lead/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-lead/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-lead/flicker-4.svg`,
    ],
  },
  "portfolio.intro.line.0": {
    width: 1323,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-intro-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.intro.line.1": {
    width: 1316,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-intro-line-1/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-1/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-1/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-1/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-1/flicker-4.svg`,
    ],
  },
  "portfolio.intro.line.2": {
    width: 1182,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-intro-line-2/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-2/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-2/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-2/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-2/flicker-4.svg`,
    ],
  },
  "portfolio.intro.line.3": {
    width: 1292,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-intro-line-3/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-3/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-3/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-3/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-3/flicker-4.svg`,
    ],
  },
  "portfolio.intro.line.4": {
    width: 1275,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-intro-line-4/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-4/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-4/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-4/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-intro-line-4/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.label.line.0": {
    width: 1413,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-label-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-label-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-label-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-label-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-label-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.title.line.0": {
    width: 1399,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.body.line.0": {
    width: 1164,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.body.line.1": {
    width: 1276,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-1/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-1/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-1/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-1/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-1/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.body.line.2": {
    width: 1337,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-2/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-2/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-2/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-2/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-body-line-2/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.artwork.0.title.line.0": {
    width: 1163,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.artwork.0.year.line.0": {
    width: 1496,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-year-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-year-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-year-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-year-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-0-year-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.artwork.1.title.line.0": {
    width: 1166,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.artwork.1.year.line.0": {
    width: 1496,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-year-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-year-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-year-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-year-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-1-year-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.artwork.2.title.line.0": {
    width: 1294,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.artworks.artwork.2.year.line.0": {
    width: 1496,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-year-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-year-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-year-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-year-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-artworks-artwork-2-year-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.label.line.0": {
    width: 1325,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-label-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-label-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-label-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-label-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-label-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.title.line.0": {
    width: 1082,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.body.line.0": {
    width: 1238,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.body.line.1": {
    width: 1512,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-1/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-1/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-1/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-1/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-1/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.body.line.2": {
    width: 1263,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-2/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-2/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-2/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-2/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-2/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.body.line.3": {
    width: 1190,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-3/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-3/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-3/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-3/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-body-line-3/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.video.0.title.line.0": {
    width: 1250,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.video.0.meta.line.0": {
    width: 1502,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-meta-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-meta-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-meta-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-meta-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-0-meta-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.video.1.title.line.0": {
    width: 1455,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.videos.video.1.meta.line.0": {
    width: 1502,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-meta-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-meta-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-meta-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-meta-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-videos-video-1-meta-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.label.line.0": {
    width: 1165,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-label-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-label-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-label-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-label-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-label-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.title.line.0": {
    width: 1430,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.body.line.0": {
    width: 1372,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.body.line.1": {
    width: 1209,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-1/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-1/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-1/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-1/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-1/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.body.line.2": {
    width: 1375,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-2/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-2/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-2/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-2/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-body-line-2/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.0.meta.line.0": {
    width: 1251,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-meta-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-meta-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-meta-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-meta-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-meta-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.0.title.line.0": {
    width: 1377,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.0.artist.line.0": {
    width: 1461,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-artist-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-artist-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-artist-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-artist-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-artist-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.0.duration.line.0": {
    width: 1187,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-duration-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-duration-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-duration-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-duration-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-0-duration-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.1.meta.line.0": {
    width: 1573,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-meta-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-meta-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-meta-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-meta-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-meta-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.1.title.line.0": {
    width: 1440,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.1.artist.line.0": {
    width: 1461,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-artist-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-artist-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-artist-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-artist-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-artist-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.1.duration.line.0": {
    width: 1348,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-duration-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-duration-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-duration-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-duration-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-1-duration-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.2.meta.line.0": {
    width: 1267,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-meta-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-meta-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-meta-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-meta-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-meta-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.2.title.line.0": {
    width: 1251,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-title-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-title-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-title-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-title-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-title-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.2.artist.line.0": {
    width: 1461,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-artist-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-artist-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-artist-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-artist-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-artist-line-0/flicker-4.svg`,
    ],
  },
  "portfolio.showcase.audio.track.2.duration.line.0": {
    width: 1585,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-duration-line-0/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-duration-line-0/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-duration-line-0/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-duration-line-0/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}portfolio-showcase-audio-track-2-duration-line-0/flicker-4.svg`,
    ],
  },
  "projects.heading": {
    width: 1352,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}projects-heading/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}projects-heading/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}projects-heading/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}projects-heading/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}projects-heading/flicker-4.svg`,
    ],
  },
  "projects.lead": {
    width: 1364,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}projects-lead/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}projects-lead/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}projects-lead/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}projects-lead/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}projects-lead/flicker-4.svg`,
    ],
  },
  "contact.heading": {
    width: 1134,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}contact-heading/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}contact-heading/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}contact-heading/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}contact-heading/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}contact-heading/flicker-4.svg`,
    ],
  },
  "contact.lead": {
    width: 1254,
    height: 52,
    maxGlyphs: 64,
    base: `${TIMESCAN_STRIP_BASE}contact-lead/base.svg`,
    flicker: [
      `${TIMESCAN_STRIP_BASE}contact-lead/flicker-1.svg`,
      `${TIMESCAN_STRIP_BASE}contact-lead/flicker-2.svg`,
      `${TIMESCAN_STRIP_BASE}contact-lead/flicker-3.svg`,
      `${TIMESCAN_STRIP_BASE}contact-lead/flicker-4.svg`,
    ],
  },
}

export default timescanGlyphStrips
export { timescanGlyphStrips }

