export const timescanAssetDefinitions = [
  {
    key: "services.eyebrow",
    text: "Services",
    minGlyphs: 4,
    targetGlyphs: 10,
  },
  {
    key: "services.heading",
    text: "Select your choice",
    minGlyphs: 8,
    targetGlyphs: 28,
  },
  {
    key: "services.lead",
    text: "Choose the lane that fits your session and goals.",
    minGlyphs: 6,
    targetGlyphs: 20,
  },
  {
    key: "services.studio-rental.title",
    text: "studio-rental:title:Studio Rental",
    minGlyphs: 6,
    targetGlyphs: 18,
  },
  {
    key: "services.studio-rental.image",
    text: "studio-rental:image:Studio PNG",
    minGlyphs: 4,
    targetGlyphs: 14,
  },
  {
    key: "services.studio-rental.bullet.0",
    text: "studio-rental:bullet:0:Hourly and half-day booking windows",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.studio-rental.bullet.1",
    text: "studio-rental:bullet:1:Control room plus live room access",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.studio-rental.bullet.2",
    text: "studio-rental:bullet:2:Add-on engineer support available",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.studio-rental.bullet.3",
    text: "studio-rental:bullet:3:Late-night sessions by request",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.music-teaching.title",
    text: "music-teaching:title:Music Teaching",
    minGlyphs: 6,
    targetGlyphs: 18,
  },
  {
    key: "services.music-teaching.image",
    text: "music-teaching:image:Teaching PNG",
    minGlyphs: 4,
    targetGlyphs: 14,
  },
  {
    key: "services.music-teaching.bullet.0",
    text: "music-teaching:bullet:0:Private one-on-one lesson blocks",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.music-teaching.bullet.1",
    text: "music-teaching:bullet:1:Beginner through advanced coaching",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.music-teaching.bullet.2",
    text: "music-teaching:bullet:2:Technique, songwriting, and performance",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.music-teaching.bullet.3",
    text: "music-teaching:bullet:3:Structured plans with weekly goals",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.other-services.title",
    text: "other-services:title:Other Services",
    minGlyphs: 6,
    targetGlyphs: 18,
  },
  {
    key: "services.other-services.image",
    text: "other-services:image:Other PNG",
    minGlyphs: 4,
    targetGlyphs: 14,
  },
  {
    key: "services.other-services.bullet.0",
    text: "other-services:bullet:0:Vocal tracking and comp preparation",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.other-services.bullet.1",
    text: "other-services:bullet:1:Demo polish and arrangement feedback",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.other-services.bullet.2",
    text: "other-services:bullet:2:Mix-ready stem export workflow",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "services.other-services.bullet.3",
    text: "other-services:bullet:3:Custom project support by scope",
    minGlyphs: 5,
    targetGlyphs: 18,
  },
  {
    key: "portfolio.heading",
    text: "Portfolio",
    minGlyphs: 4,
    targetGlyphs: 24,
  },
  {
    key: "portfolio.lead",
    text: "Your gateway to all things Foxgote.",
    minGlyphs: 5,
    targetGlyphs: 24,
  },
]
